name: BlueMapMarkers
version: '1.0'
main: org.siberianhusy.BlueMapMarkers
api-version: '1.19'

commands:
  BlueMapMarkers:
    description: BlueMap标记添加
    aliases: bmm
  bmgui:
    description: BlueMapMarkersGUI界面
  BlueMapMarkersAdmin:
    aliases: bmma
    description: BlueMapMarkers管理员命令
    permission: bluemapmarkers.admin
    permission-message: 你没有权限！


